# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-11-26 03:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_auto_20171125_1409'),
    ]

    operations = [
        migrations.RenameField(
            model_name='application',
            old_name='student_id',
            new_name='username',
        ),
        migrations.RenameField(
            model_name='attendance',
            old_name='student_id',
            new_name='username',
        ),
        migrations.RenameField(
            model_name='review',
            old_name='student_id',
            new_name='username',
        ),
        migrations.AlterField(
            model_name='student',
            name='food_restrictions',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterUniqueTogether(
            name='application',
            unique_together=set([('username', 'dinner_id')]),
        ),
        migrations.AlterUniqueTogether(
            name='attendance',
            unique_together=set([('username', 'dinner_id')]),
        ),
        migrations.AlterUniqueTogether(
            name='review',
            unique_together=set([('username', 'dinner_id')]),
        ),
    ]
