# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-12-03 16:53
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_auto_20171203_1641'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='attendance',
            options={'verbose_name': 'Attendance', 'verbose_name_plural': 'Attendance'},
        ),
        migrations.AlterModelOptions(
            name='selection',
            options={'verbose_name': 'Selection', 'verbose_name_plural': 'Selection'},
        ),
    ]
