# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2017-12-13 14:20
from __future__ import unicode_literals

import app.models
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_auto_20171212_1822'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='netid',
            field=models.CharField(max_length=7, unique=True, validators=[django.core.validators.RegexValidator(regex=b'^[a-zA-Z]+[0-9]+')]),
        ),
        migrations.AlterField(
            model_name='student',
            name='unique_id',
            field=models.CharField(max_length=7, unique=True, validators=[app.models.validate_unique_id]),
        ),
    ]
